// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: aelf_options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Aelf {

  /// <summary>Holder for reflection information generated from aelf_options.proto</summary>
  public static partial class AelfOptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for aelf_options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AelfOptionsReflection()
    {
      byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJhZWxmX29wdGlvbnMucHJvdG8SBGFlbGYaIGdvb2dsZS9wcm90b2J1Zi9k",
          "ZXNjcmlwdG9yLnByb3RvOjcKDGNzaGFycF9zdGF0ZRIfLmdvb2dsZS5wcm90",
          "b2J1Zi5TZXJ2aWNlT3B0aW9ucxjFxA4gASgJOjEKB2lzX3ZpZXcSHi5nb29n",
          "bGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxjr9hQgASgIOjMKCGlzX2V2ZW50",
          "Eh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGIOeMyABKAg6MwoK",
          "aXNfaW5kZXhlZBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYmZMh",
          "IAEoCA=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
