// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: aelf_options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Aelf {

  /// <summary>Holder for reflection information generated from aelf_options.proto</summary>
  public static partial class AelfOptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for aelf_options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AelfOptionsReflection()
    {
      byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJhZWxmX29wdGlvbnMucHJvdG8SBGFlbGYaIGdvb2dsZS9wcm90b2J1Zi9k",
          "ZXNjcmlwdG9yLnByb3RvOi8KBGJhc2USHy5nb29nbGUucHJvdG9idWYuU2Vy",
          "dmljZU9wdGlvbnMYqekeIAMoCTo3Cgxjc2hhcnBfc3RhdGUSHy5nb29nbGUu",
          "cHJvdG9idWYuU2VydmljZU9wdGlvbnMYxukeIAEoCToxCgdpc192aWV3Eh4u",
          "Z29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMYkfEeIAEoCDozCghpc19l",
          "dmVudBIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxi0hwMgASgI",
          "OjMKCmlzX2luZGV4ZWQSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25z",
          "GPHRHiABKAg="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
