site_name: AELF
theme:
  name: material
  features:
    - tabs
  logo: img/logo.svg
  favicon: img/favicon.png
  palette:
    primary: cyan
    accent: cyan
  font:
    text: Ubuntu
    code: Ubuntu Mono

repo_name: AElfProject/AElf
repo_url: https://github.com/AElfProject/

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk

markdown_extensions:
  - toc:
      permalink: true


nav:
  - Introduction : 'index.md'
  - Tutorials : 'tutorials/main.md'
  - Tutorials:
    - 'Environment setup' : 'tutorials/setup/setup.md'
    # - 'Running a node' : 'tutorials/setup/main.md'
    - 'Single node' : 'tutorials/setup/docker.md'
    - 'Multi node' : 'tutorials/setup/docker-multi-node.md'
    - 'Build and run sources' : 'tutorials/setup/run-node.md'
    - 'Smart contract development' : 'tutorials/developing-smart-contracts/main.md'
    - 'Setup Boilerplate' : 'tutorials/developing-smart-contracts/setup.md'
    - 'First contract - implement' : 'tutorials/developing-smart-contracts/first-contract.md'
    - 'First contract - test' : 'tutorials/developing-smart-contracts/first-contract-test.md'
    - 'First contract - deploy' : 'tutorials/developing-smart-contracts/first-contract-deploy.md'
    - 'First contract - front end' : 'tutorials/developing-smart-contracts/front.md'
    - 'Execution context' : 'tutorials/developing-smart-contracts/tx-execution-context.md'
    - 'Inline contract calls' : 'tutorials/developing-smart-contracts/internal-contract-call.md'
    - 'Enterprise development' : 'tutorials/enterprise.md'
    # - 'Cross-chain' : 'tutorials/cross-chain/main.md'
    - 'Request side-chain creation' : 'tutorials/cross-chain/request-new-side-chain.md'

  - AElf protocol : 'protocol/main.md'
  - AElf protocol:
    - 'Addresses' : 'protocol/addresses.md'
    - 'Transactions' : 'protocol/transactions.md'
    - 'Blocks' : 'protocol/blocks.md'
    - 'Consensus' : 'protocol/consensus.md'

  - Smart contracts : 'contract/main.md'
  - Smart contracts:
    - 'Architecture' : 'contract/architecture.md'
    - 'Service' : 'contract/service.md'
    - 'Event' : 'contract/events.md'
    - 'Messages' : 'contract/messages.md'
    - 'Deploy guide' : 'contract/deployment.md'
    - 'AELF Contract Standard' : 'contract/acs.md'
    - 'Requirements and Restrictions' : 'contract/requirements-restrictions.md'
    - 'Project Requirements' : 'contract/restrictions/project.md'
    - 'Structure Restrictions and Requirements' : 'contract/restrictions/structure.md'
    - 'Namespace and Type Restrictions' : 'contract/restrictions/type.md'
    - 'Other Restrictions' : 'contract/restrictions/others.md'

  - Cross chain : 'crosschain/main.md'
  - Cross chain:
    - 'Introduction' : 'crosschain/introduction.md'
    - 'Architecture' : 'crosschain/architecture.md'
    - 'Crosschain verification' : 'crosschain/crosschain-verification.md'
    - 'Creation' : 'crosschain/setup.md'
    - 'Verify' : 'crosschain/verify.md'
    - 'Transfer' : 'crosschain/transfer.md'

  - AElf mainnet/testnet : 'public-chain/main.md'
  - AElf mainnet/testnet:
    - 'Introduction' : 'public-chain/introduction.md'
    - 'AElf consensus' : 'public-chain/dpos.md'
    - 'Crosschain tokens' : 'public-chain/crosschain-multitoken.md'
    - 'Resource system' : 'public-chain/resources.md'
    - 'Authority contracts' : 'public-chain/auth-contract.md'

  - Architecture : 'architecture/main.md'
  - Architecture:
    - 'Introduction' : 'architecture/introduction.md'
    - 'Implementations' : 'architecture/implementations.md'

  - Contribution : 'devops/devops.md'
  - Contribution:
    - 'DevOps' : 'devops/devops.md'

  - Web api reference : 'web-api-reference/reference.md'
  - Web api reference:
    - 'Web api reference' : 'web-api-reference/reference.md'

  # - Chain SDK reference : 'sdk/js.md' 
  - Chain SDK reference : 'sdk/javascript/js-sdk.md'
  - Chain SDK reference:
    - 'JS SDK' : 'sdk/javascript/js-sdk.md'
    - 'C# SDK' : 'sdk/csharp/csharp-sdk.md'
    - 'Go SDK' : 'sdk/go/go-sdk.md'
    - 'Java SDK' : 'sdk/java/java-sdk.md'
    - 'PHP SDK' : 'sdk/php/php-sdk.md'
    - 'Python SDK' : 'sdk/py/py-sdk.md'
    - 'dApp SDK' : 'sdk/javascript/dapp-sdk.md'

  - Contract SDK reference : 'sdk/contract-sdk.md'
  - Contract SDK reference:
    - 'C# reference' : 'sdk/csharp/main.md'
    - 'AElf.SDK.CSharp' : 'sdk/csharp/contract-sdk.md'
    - 'AElf.CSharp.Core' : 'sdk/csharp/core-sdk.md'

  - Resources: 'resources/resources.md'
  - Resources:
    - 'Smart Contract APIs' : 'resources/smart-contract-apis/index.md'
    - 'Association Contract' : 'resources/smart-contract-apis/association.md'
    - 'Referendum Contract' : 'resources/smart-contract-apis/referendum.md'
    - 'Parliament Contract' : 'resources/smart-contract-apis/parliament.md'
    - 'Consensus Contract' : 'resources/smart-contract-apis/consensus.md'
    - 'Election Contract' : 'resources/smart-contract-apis/election.md'
    - 'Genesis Contract' : 'resources/smart-contract-apis/genesis.md'
    - 'Multi Token Contract' : 'resources/smart-contract-apis/multi-token.md'
    - 'Profit Contract' : 'resources/smart-contract-apis/profit.md'
    - 'Resource Contract' : 'resources/smart-contract-apis/resource.md'
    - 'Cross chain Contract' : 'resources/smart-contract-apis/cross-chain.md'
    - 'Treasury Contract' : 'resources/smart-contract-apis/treasury.md'
    - 'Vote Contract' : 'resources/smart-contract-apis/vote.md'
    - 'Token Holder Contract' : 'resources/smart-contract-apis/token-holder.md'
    - 'Wallet and Block Explorer' : 'resources/wallet-and-explorer/index.md'
    - 'explorer-api' : 'resources/wallet-and-explorer/explorer-api.md'
    # - 'Command line interface' : 'resources/cli/cli.md'
    # - 'Introduction' : 'resources/cli/introduction.md'
    - 'Command line interface' : 'resources/cli/introduction.md'
    - 'Commands' : 'resources/cli/methods.md'
    - 'Running AElf on the cloud' : 'resources/cloud/main.md'
    - 'Google cloud' : 'resources/cloud/gcp/GCP.md'
    - 'Browser Extension' : 'resources/browser-extension.md'
    - 'Joining AElf testnet' : 'resources/testnet.md'
    - 'Running a side chain' : 'tutorials/cross-chain/running-side-chain.md'

    
  
  