// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf {

  /// <summary>Holder for reflection information generated from options.proto</summary>
  public static partial class OptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1vcHRpb25zLnByb3RvEgRhZWxmGiBnb29nbGUvcHJvdG9idWYvZGVzY3Jp",
            "cHRvci5wcm90bzowCghpZGVudGl0eRIcLmdvb2dsZS5wcm90b2J1Zi5GaWxl",
            "T3B0aW9ucxihwh4gASgJOi8KBGJhc2USHy5nb29nbGUucHJvdG9idWYuU2Vy",
            "dmljZU9wdGlvbnMYqekeIAMoCTo3Cgxjc2hhcnBfc3RhdGUSHy5nb29nbGUu",
            "cHJvdG9idWYuU2VydmljZU9wdGlvbnMYxukeIAEoCToxCgdpc192aWV3Eh4u",
            "Z29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMYkfEeIAEoCDozCghpc19l",
            "dmVudBIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxi0hwMgASgI",
            "OjMKCmlzX2luZGV4ZWQSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25z",
            "GPHRHiABKAhCB6oCBEFFbGY="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { OptionsExtensions.Identity, OptionsExtensions.Base, OptionsExtensions.CsharpState, OptionsExtensions.IsView, OptionsExtensions.IsEvent, OptionsExtensions.IsIndexed }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of options.proto</summary>
  public static partial class OptionsExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FileOptions, string> Identity =
      new pb::Extension<global::Google.Protobuf.Reflection.FileOptions, string>(500001, pb::FieldCodec.ForString(4000010, ""));
    public static readonly pb::RepeatedExtension<global::Google.Protobuf.Reflection.ServiceOptions, string> Base =
      new pb::RepeatedExtension<global::Google.Protobuf.Reflection.ServiceOptions, string>(505001, pb::FieldCodec.ForString(4040010));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, string> CsharpState =
      new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, string>(505030, pb::FieldCodec.ForString(4040242, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool> IsView =
      new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool>(506001, pb::FieldCodec.ForBool(4048008, false));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool> IsEvent =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool>(50100, pb::FieldCodec.ForBool(400800, false));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> IsIndexed =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(502001, pb::FieldCodec.ForBool(4016008, false));
  }

}

#endregion Designer generated code
