// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hashpair.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Contracts.Token {

  /// <summary>Holder for reflection information generated from hashpair.proto</summary>
  public static partial class HashpairReflection {

    #region Descriptor
    /// <summary>File descriptor for hashpair.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HashpairReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5oYXNocGFpci5wcm90bxoKaGFzaC5wcm90byI3CghIYXNoUGFpchIUCgVG",
            "aXJzdBgBIAEoCzIFLkhhc2gSFQoGU2Vjb25kGAIgASgLMgUuSGFzaEIXqgIU",
            "QUVsZi5Db250cmFjdHMuVG9rZW5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Kernel.HashReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Token.HashPair), global::AElf.Contracts.Token.HashPair.Parser, new[]{ "First", "Second" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class HashPair : pb::IMessage<HashPair> {
    private static readonly pb::MessageParser<HashPair> _parser = new pb::MessageParser<HashPair>(() => new HashPair());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HashPair> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Token.HashpairReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HashPair() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HashPair(HashPair other) : this() {
      First = other.first_ != null ? other.First.Clone() : null;
      Second = other.second_ != null ? other.Second.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HashPair Clone() {
      return new HashPair(this);
    }

    /// <summary>Field number for the "First" field.</summary>
    public const int FirstFieldNumber = 1;
    private global::AElf.Kernel.Hash first_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AElf.Kernel.Hash First {
      get { return first_; }
      set {
        first_ = value;
      }
    }

    /// <summary>Field number for the "Second" field.</summary>
    public const int SecondFieldNumber = 2;
    private global::AElf.Kernel.Hash second_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AElf.Kernel.Hash Second {
      get { return second_; }
      set {
        second_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HashPair);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HashPair other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(First, other.First)) return false;
      if (!object.Equals(Second, other.Second)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (first_ != null) hash ^= First.GetHashCode();
      if (second_ != null) hash ^= Second.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (first_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(First);
      }
      if (second_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Second);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (first_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(First);
      }
      if (second_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Second);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HashPair other) {
      if (other == null) {
        return;
      }
      if (other.first_ != null) {
        if (first_ == null) {
          first_ = new global::AElf.Kernel.Hash();
        }
        First.MergeFrom(other.First);
      }
      if (other.second_ != null) {
        if (second_ == null) {
          second_ = new global::AElf.Kernel.Hash();
        }
        Second.MergeFrom(other.Second);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (first_ == null) {
              first_ = new global::AElf.Kernel.Hash();
            }
            input.ReadMessage(first_);
            break;
          }
          case 18: {
            if (second_ == null) {
              second_ = new global::AElf.Kernel.Hash();
            }
            input.ReadMessage(second_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
