blank_issues_enabled: false
issue_template:
  - name: 👾 Bug Report
    description: Report a bug or issue with the project.
    labels: ["bug"]
    template: bug_report.md
  - name: 💡 Feature Request
    description: Create a new ticket for a new feature request.
    labels: ["enhancement"]
    template: feature_request.md