# File: build-template-linux.yml
parameters:
  - name: parts
    type: number
  - name: n
    type: number
  - name: codecoverage
    type: boolean
    default: false

# All tasks on Linux
jobs:
- job: build_all_linux_${{ parameters.n }}
  displayName: Build tasks (Linux) [${{ parameters.n }} of ${{ parameters.parts }} parts]
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-22.04
  variables:
    CI_TEST: true
  steps:
    - script: |
        echo "=== Disk space before cleanup ==="
        df -h /
        # Remove unnecessary pre-installed software to free disk space
        sudo rm -rf /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6.* || true
        sudo rm -rf /usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.* || true
        sudo rm -rf /usr/share/dotnet/shared/Microsoft.NETCore.App/6.* || true
        sudo rm -rf /usr/share/dotnet/shared/Microsoft.NETCore.App/7.* || true
        sudo rm -rf /usr/local/lib/android || true
        sudo rm -rf /opt/ghc || true
        sudo rm -rf /usr/share/swift || true
        sudo rm -rf /usr/local/share/powershell || true
        sudo rm -rf /usr/local/share/chromium || true
        sudo rm -rf /usr/local/.ghcup || true
        # Clean apt cache
        sudo apt-get clean || true
        # Clean Docker images
        docker system prune -af || true
        echo "=== Disk space after cleanup ==="
        df -h /
      displayName: 'Free disk space'
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        version: 8.0.303
    - script: bash scripts/install_protobuf.sh
    - script: bash scripts/download_binary.sh
    - script: bash build.sh --target=Test-with-Codecov-N --parts=${{ parameters.parts }} --number=${{ parameters.n }} --codecoverage=${{ parameters.codecoverage }}
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'

    - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
      displayName: ReportGenerator
      inputs:
        reports: '$(Build.SourcesDirectory)/test/*/TestResults/*/coverage.cobertura.xml'
        targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
        reporttypes: 'Cobertura'
        assemblyfilters: '-xunit*'
    - script: bash build.sh --target=Upload-Coverage-Azure
      displayName: 'Upload data to Codecov'