name: Build
on:
  push:
    branches:
      - dev
      - master
      - feature/use-github-actions

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Download AElf build tools
        run: bash scripts/download_binary.sh

      - name: Install Protobuf
        run: bash scripts/install_protobuf.sh

      - name: Build Solution
        run: bash scripts/build.sh

