on:
  push:
    branches:
      - preview

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read version from version.props
        run: |
          version=$(grep -oP '<Version>\K[^<]+' common.props)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Determine if preview version
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/preview" ]]; then
            echo "IS_PREVIEW=true" >> $GITHUB_ENV
          else
            echo "IS_PREVIEW=false" >> $GITHUB_ENV
          fi

      - name: Pack
        run: dotnet pack AElf.All.sln --configuration Release --output nupkgs /p:Version=$VERSION /p:Platform="Any CPU"

      - name: Publish NuGet packages
        uses: dansiegel/publish-nuget@v1.2
        with:
          filename: '**/*.nupkg'
          apiKey: ${{ secrets.PREVIEW_NUGET_API_KEY }}
          feedUrl: ${{ secrets.PREVIEW_NUGET_FEED_URL }}
