on:
  push:
    branches:
      - preview

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Read version from version.props
        run: |
          version=$(grep -oP '<Version>\K[^<]+' common.props)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Determine if preview version
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/preview" ]]; then
            echo "IS_PREVIEW=true" >> $GITHUB_ENV
          else
            echo "IS_PREVIEW=false" >> $GITHUB_ENV
          fi

      - name: Pack
        run: dotnet pack --configuration Release --output nupkgs /p:Version=$VERSION

      - name: Publish
        if: env.IS_PREVIEW == 'true'
        uses: nuget/publish@v1
        with:
          nuget_key: ${{ secrets.PREVIEW_NUGET_API_KEY }}
          nuget_source: ${{ secrets.PREVIEW_NUGET_FEED_URL }}
          version: $VERSION-preview.${GITHUB_RUN_NUMBER}
          package: '**/*.nupkg'

      - name: Publish
        if: env.IS_PREVIEW != 'true'
        uses: nuget/publish@v1
        with:
          nuget_key: ${{ secrets.NUGET_API_KEY }}
          nuget_source: ${{ secrets.NUGET_FEED_URL }}
          version: $VERSION
          package: '**/*.nupkg'
